### PR TITLE
Initial README.md commit

### PR DESCRIPTION
**Pull request by gked**
This is the initial version of README.md file.  I will be making changes to the file in the following PRs. 
I didn't want to start with a modified version of the file since it would be hard to track the changes.

### CODE REVIEW

**Comment by gked** [comment]
@pocketnetteam @andyoknen as FYI for the review.

This is an agreed-upon course of action from here: https://github.com/pocketnetteam/pocketnet.core/issues/481

**Comment by andyoknen** [comment]
> @pocketnetteam @andyoknen as FYI for the review.
> 
> 
> 
> This is an agreed-upon course of action from here: https://github.com/pocketnetteam/pocketnet.core/issues/481

Thank you! Great start!

I think we could adjust the title to give the idea of ​​the core platform in the title - Pocketnet as a platform for the decentralized web3 network.  Bastyon is only part of the overall idea and one of the applications within the PocketNet.

I will update the repository once your PR is accepted so we can discuss it.

**Review by andyoknen — APPROVED** [review]

**Comment by gked** [comment]
@andyoknen I see - thank you for the clarification. I've been thinking about Bastyon as a rebranding for Pocketnet which may have been a misunderstanding on my part. 
So Pocketnet is the name of the blockchain protocol and its ecosystem and Bastyon is the name of the application? Is this the right  way to think about it?
I have made changes to the README.md as part of another PR which I will send once this one gets merged. We could use that PR to discuss the subtleties of the project vision and its goals. So we can iterate on that new version of the README.md file to match your expectations.

**Comment by andyoknen** [comment]
@gked you got me absolutely right!  tonight I will accept the first PR - I made an access request from pocketnetteam

**Review by only1question — APPROVED** [review]

**Review by andyoknen — APPROVED** [review]

**Pull request merged**
